# -*- coding: utf-8 -*-

"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8QPjA0RVGecOxE0YoS5LKnPAvfMnfQw
"""

import chess
import chess.pgn
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import IterableDataset, DataLoader

def board_to_matrix(board):
    matrix = np.zeros((12, 8, 8), dtype=np.float32)
    piece_map = board.piece_map()

    for square, piece in piece_map.items():
        row = 7 - (square // 8)
        col = square % 8
        piece_type = piece.piece_type - 1
        if not piece.color:
            piece_type += 6
        matrix[piece_type, row, col] = 1.0
    return matrix

def move_to_index(move):
    return move.from_square * 64 + move.to_square

class ChessPGNDataset(IterableDataset):
    def __init__(self, pgn_path, max_games=5000):
        self.pgn_path = pgn_path
        self.max_games = max_games

    def __iter__(self):
        pgn = open(self.pgn_path, errors="ignore")
        games_count = 0

        while games_count < self.max_games:
            game = chess.pgn.read_game(pgn)

            if game is None:
                break

            board = game.board()
            for move in game.mainline_moves():
                x = board_to_matrix(board)
                y = move_to_index(move)

                yield x, y
                board.push(move)

            games_count += 1
        pgn.close()

class ChessNet(nn.Module):
    def __init__(self):
        super(ChessNet, self).__init__()
        self.conv1 = nn.Conv2d(12, 64, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(128, 128, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(128 * 8 * 8, 1024)
        self.fc2 = nn.Linear(1024, 4096)

    def forward(self, x):
        x = torch.relu(self.conv1(x))
        x = torch.relu(self.conv2(x))
        x = torch.relu(self.conv3(x))
        x = x.view(-1, 128 * 8 * 8)
        x = torch.relu(self.fc1(x))
        return self.fc2(x)

def train():
    PGN_FILE = "lichess_elite_2022-05.pgn"
    BATCH_SIZE = 256
    EPOCHS = 3
    LEARNING_RATE = 0.001

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = ChessNet().to(device)
    optimizer = optim.Adam(model.parameters(), lr = LEARNING_RATE)
    criterion = nn.CrossEntropyLoss()

    dataset = ChessPGNDataset(PGN_FILE, max_games = 10_000)
    dataloader = DataLoader(dataset, batch_size = BATCH_SIZE)

    model.train()

    for epoch in range(EPOCHS):
        running_loss = 0.0
        batch_count = 0

        for inputs, labels in dataloader:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()

            outputs = model(inputs)
            loss = criterion(outputs, labels)

            loss.backward()
            optimizer.step()
            batch_count += 1

            print(f"Эпоха {epoch+1}/{EPOCHS} | Батч {batch_count} | Ошибка (Loss): {loss.item():.4f}")

    torch.save(model.state_dict(), "chess_bot.pth")